# Generated by Django 5.0.6 on 2024-07-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UTNSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fathers', models.CharField(max_length=100)),
                ('children', models.CharField(max_length=100)),
            ],
        ),
    ]
