# Generated by Django 5.0.6 on 2024-07-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainTree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utnsubject',
            name='children',
        ),
        migrations.RemoveField(
            model_name='utnsubject',
            name='fathers',
        ),
        migrations.AddField(
            model_name='utnsubject',
            name='approval_children',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utnsubject',
            name='approval_fathers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utnsubject',
            name='regular_children',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='utnsubject',
            name='regular_fathers',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
