# Generated by Django 5.0.6 on 2024-07-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainTree', '0002_remove_utnsubject_children_remove_utnsubject_fathers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UTNSubject',
            new_name='UTNSistemasSubject',
        ),
    ]
