# Generated by Django 5.0.6 on 2024-07-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainTree', '0003_rename_utnsubject_utnsistemassubject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UTNSistemasSubject',
            new_name='UTNSubject',
        ),
    ]
