# Generated by Django 5.0.6 on 2024-07-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainTree', '0004_rename_utnsistemassubject_utnsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='utnsubject',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
