# Generated by Django 5.0.6 on 2024-08-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainTree', '0005_utnsubject_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UTNSubject',
            new_name='UTNSubjectSistemas',
        ),
    ]
