# Generated by Django 5.0.6 on 2024-08-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainTree', '0006_rename_utnsubject_utnsubjectsistemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTNSubjectCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('approval_fathers', models.CharField(blank=True, max_length=100)),
                ('approval_children', models.CharField(blank=True, max_length=100)),
                ('regular_fathers', models.CharField(blank=True, max_length=100)),
                ('regular_children', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UTNSubjectElectrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('approval_fathers', models.CharField(blank=True, max_length=100)),
                ('approval_children', models.CharField(blank=True, max_length=100)),
                ('regular_fathers', models.CharField(blank=True, max_length=100)),
                ('regular_children', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UTNSubjectElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('approval_fathers', models.CharField(blank=True, max_length=100)),
                ('approval_children', models.CharField(blank=True, max_length=100)),
                ('regular_fathers', models.CharField(blank=True, max_length=100)),
                ('regular_children', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UTNSubjectIndustrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('approval_fathers', models.CharField(blank=True, max_length=100)),
                ('approval_children', models.CharField(blank=True, max_length=100)),
                ('regular_fathers', models.CharField(blank=True, max_length=100)),
                ('regular_children', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UTNSubjectMecanica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('approval_fathers', models.CharField(blank=True, max_length=100)),
                ('approval_children', models.CharField(blank=True, max_length=100)),
                ('regular_fathers', models.CharField(blank=True, max_length=100)),
                ('regular_children', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UTNSubjectMetalurgica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('approval_fathers', models.CharField(blank=True, max_length=100)),
                ('approval_children', models.CharField(blank=True, max_length=100)),
                ('regular_fathers', models.CharField(blank=True, max_length=100)),
                ('regular_children', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UTNSubjectQuimica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('approval_fathers', models.CharField(blank=True, max_length=100)),
                ('approval_children', models.CharField(blank=True, max_length=100)),
                ('regular_fathers', models.CharField(blank=True, max_length=100)),
                ('regular_children', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
