# Generated by Django 5.0.6 on 2024-08-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainTree', '0008_alter_utnsubjectcivil_approval_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utnsubjectcivil',
            name='all_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utnsubjectelectrica',
            name='all_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utnsubjectelectronica',
            name='all_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utnsubjectindustrial',
            name='all_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utnsubjectmecanica',
            name='all_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utnsubjectmetalurgica',
            name='all_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utnsubjectquimica',
            name='all_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utnsubjectsistemas',
            name='all_approved',
            field=models.BooleanField(default=False),
        ),
    ]
